language: node_js
node_js: 6.6.0

sudo: required

services:
- docker

env:
  global:
  - DOCKER_EMAIL=tech@goabout.com
  - DOCKER_USERNAME=goabouttech
  # DOCKER_PASSWORD
  - secure: YD6snmt+VPbx9kaXQLqsB0MDv0Y7vwQW0PbYzP+q9cC1PrmDRvq2BsNk1E1wmXqHecLZjUErISkZKsenYpNHfMvz90bi7BPPNgKszC+XNJ6RPjN3PtMlA/FjVkS6XTsS09XxdePEdpBnB4MgCoBP8c9BZRqs5KtAPPOdYa0Ku9WNzhdT4tx6bIV4jobZnoj1E1aXodV9KGzLsxJ4YNIjD/c+5jZLpJwq1AoeC52jimbXdf5hyflRobdwGYNIqgShIBZBF0jTIqWyxgxdcOuBwfDZXzxFwW0K20RRijRPw2EfN1RVZ3IJe6FPs27O5m7XF1CxO0s4naATeZkA+xPmoo9V2HXZEjyVkfCj5716eYHtnZ7Ubfiwu7SXJKp2lQuFREkAZCAwhp1W9QkKWCyGJAXkZuraOAmjFRueIvstgjEPNfxAEzxL9V1ZgrUQmrZAhqnk5IDYsTQXs2fpIc5c1rvySNANWGeNzKKVCYX3L4xCG5EoIpm2AYC7Bh18Ijmk0nYmAv5B26fBVPh+4i314SwHy7x7eD98bXBJQI+UUzT8vVPmmapEKwqnf03Pq+TPf3YvcMQ0jpQJtsRvABQEDUPbmpUDUontkIqnFPmBWHp0X8aDSGyxH4Yj1lMZR3IpdEgWHoH0BcOnfWrN7kSRsH7+YCDHR55ga0cq0opnHgI=
  # ANSIBLE_VAULT_PASSWORD
  - secure: fa7jJeRjPqcnTa/NCOL2u3HTCyrDx+Cf8pOE3zQ+kE6maJF6sbBirDI0xunQLLBbkO6Crvu6mweaH4mowid4wWm82VkQOAsFhwbN3WA4ffQj057CCRn7IVkmU49pGifAFRBxv2UMRM3MvIU8kUvDNiFRd4DdkxMyhuXtGvZ93HSXCOnzSJpPVOAwas3TXmbsqh49PT3OEBYU9W9oYoedZHzlwcFn/oEwK6keh1m94bN8L1LVnsduUkeiD22kPx1r2dKDQ7Kem70OIMebRJyyFwQC/9a2LyYDGMz0URpvpKeELyh7vT1ET1mRCyK+yt1QKDn84ntvedV+1ts66O/aFQe/jsYMmzb/cHkyXS5q6LA5RVpMJq8Ovl5cMCnBAPWYMq9XcsRv3LoZRousNedrG63x8c+UHiCHXZnF8nOwRq8aSTi6lfLLlPR/k5EQYuEATx9GkIxyotUc/C1tyye5aWaIczmfj0zFo02X5IspMThNvRNShQ2rk/TLDruyCyWvUOTGppTP1Uqf3TgIAscxFTaXkclq7gjsISmL9WXzJPqPssjMl5OHoqTTDyVvq8lxXEMFHPi75PgV+aKLG98PM9j8DdiUXkkLkqXBMDEz1e4f4aM9/mu5JRURl8XgWFRZculHL8Y6jzi0OCObDAR49+61Wd31v21KFfBcg38VVLY=


install: true

before_script: docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script: scripts/_integrate.sh

cache:
  apt: true
